---
deployment:
  tasks:
    # - export DEPLOYPATH=/home/eqeqmgjz/public_html/hoaanhtuc.vn/
    # - /bin/cp -R * $DEPLOYPATH
    # - rm $DEPLOYPATH/public/build/assets/style-main.css

    # - export DEPLOYPATH=/home/eqeqmgjz/public_html/thachtraquan.com/
    # - /bin/cp -R * $DEPLOYPATH
    # - rm $DEPLOYPATH/public/build/assets/style-main.css

    - export DEPLOYPATH=/home/eqeqmgjz/public_html/trumvape.com/
    - /bin/cp -R * $DEPLOYPATH
    - rm $DEPLOYPATH/public/build/assets/style-main.css

    - export DEPLOYPATH=/home/eqeqmgjz/public_html/dacsanphuquoc24h.vn/
    - /bin/cp -R * $DEPLOYPATH
    - rm $DEPLOYPATH/public/build/assets/style-main.css
    
    # - /bin/cp /app $DEPLOYPATH
    # - /bin/cp /bootstrap $DEPLOYPATH
    # - /bin/cp /config $DEPLOYPATH
    # - /bin/cp /database $DEPLOYPATH
    # - /bin/cp /lang $DEPLOYPATH
    # - /bin/cp /public $DEPLOYPATH
    # - /bin/cp /resources $DEPLOYPATH
    # - /bin/cp /routes $DEPLOYPATH
    # - /bin/cp /tests $DEPLOYPATH