<?php 

return [
    'page'  => [
        [
            'title'                     => 'Trang chủ',
            'description'               => 'Mô tả trang chủ',
            'image'                     => null,
            'image_small'               => null,
            'level'                     => 1,
            'seo_title'                 => 'Trang chủ @ thuonghieu',
            'seo_description'           => 'Mô tả ngắn về trang, dịch vụ, sản phẩm, vv',
            'slug'                      => '/',
            'slug_full'                 => '/',
            'type'                      => 'page_info',
            'rating_author_name'        => 'Thuonghieu',
            'rating_aggregate_count'    => 10,
            'rating_aggregate_star'     => 5,
            'created_by'                => 1,
            'show_sidebar'              => 0
        ],
        [
            'title'                     => 'Tìm kiếm sản phẩm',
            'description'               => 'Mô tả trang Tìm kiếm sản phẩm',
            'image'                     => null,
            'image_small'               => null,
            'level'                     => 1,
            'seo_title'                 => 'Tìm kiếm sản phẩm @ thuonghieu',
            'seo_description'           => 'Mô tả ngắn về trang Tìm kiếm sản phẩm',
            'slug'                      => 'tim-kiem-san-pham',
            'slug_full'                 => 'tim-kiem-san-pham',
            'type'                      => 'page_info',
            'rating_author_name'        => 'Thuonghieu',
            'rating_aggregate_count'    => 10,
            'rating_aggregate_star'     => 5,
            'created_by'                => 1,
            'show_sidebar'              => 0
        ],
        [
            'title'                     => 'Giỏ hàng',
            'description'               => 'Mô tả trang Giỏ hàng',
            'image'                     => null,
            'image_small'               => null,
            'level'                     => 1,
            'seo_title'                 => 'Giỏ hàng @ thuonghieu',
            'seo_description'           => 'Mô tả ngắn về trang Giỏ hàng',
            'slug'                      => 'gio-hang',
            'slug_full'                 => 'gio-hang',
            'type'                      => 'page_info',
            'rating_author_name'        => 'Thuonghieu',
            'rating_aggregate_count'    => 10,
            'rating_aggregate_star'     => 5,
            'created_by'                => 1,
            'show_sidebar'              => 0
        ],
        [
            'title'                     => 'Khuyến mãi',
            'description'               => 'Mô tả trang Khuyến mãi',
            'image'                     => null,
            'image_small'               => null,
            'level'                     => 1,
            'seo_title'                 => 'Khuyến mãi @ thuonghieu',
            'seo_description'           => 'Mô tả ngắn về trang Khuyến mãi',
            'slug'                      => 'san-pham-khuyen-mai',
            'slug_full'                 => 'san-pham-khuyen-mai',
            'type'                      => 'page_info',
            'rating_author_name'        => 'Thuonghieu',
            'rating_aggregate_count'    => 10,
            'rating_aggregate_star'     => 5,
            'created_by'                => 1,
            'show_sidebar'              => 0
        ],
        [
            'title'                     => 'Chính sách đổi /trả',
            'description'               => 'Mô tả trang Chính sách đổi /trả',
            'image'                     => null,
            'image_small'               => null,
            'level'                     => 1,
            'seo_title'                 => 'Chính sách đổi /trả @ thuonghieu',
            'seo_description'           => 'Mô tả ngắn về trang Chính sách đổi /trả',
            'slug'                      => 'chinh-sach-doi-tra',
            'slug_full'                 => 'chinh-sach-doi-tra',
            'type'                      => 'page_info',
            'rating_author_name'        => 'Thuonghieu',
            'rating_aggregate_count'    => 10,
            'rating_aggregate_star'     => 5,
            'created_by'                => 1,
            'show_sidebar'              => 0
        ],
        [
            'title'                     => 'Chính sách thu thập dữ liệu',
            'description'               => 'Mô tả trang Chính sách thu thập dữ liệu',
            'image'                     => null,
            'image_small'               => null,
            'level'                     => 1,
            'seo_title'                 => 'Chính sách thu thập dữ liệu @ thuonghieu',
            'seo_description'           => 'Mô tả ngắn về trang Chính sách thu thập dữ liệu',
            'slug'                      => 'chinh-sach-thu-thap-du-lieu',
            'slug_full'                 => 'chinh-sach-thu-thap-du-lieu',
            'type'                      => 'page_info',
            'rating_author_name'        => 'Thuonghieu',
            'rating_aggregate_count'    => 10,
            'rating_aggregate_star'     => 5,
            'created_by'                => 1,
            'show_sidebar'              => 0
        ]
    ]
];